---
- name: Create VM
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ["./vars_vm.yml"]

  tasks:
   #- name: Loading secrets
     #include_vars:
       #dir: ./
       #files_matching: secrets.yml

   - name: Checking vCenter folder (creates the folder if doesnt exists)
     vcenter_folder:
        validate_certs: "{{ vcenter_validate_certs}}"
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ vcenter_datacenter }}"
        port: "{{ vcenter_port }}"
        folder_name: "seco-test"
        folder_type: vm
        state: present
     register: "folder"


   - name: Deploying VM
     vmware_guest:
       validate_certs: "{{ vcenter_validate_certs}}"
       hostname: "{{ vcenter_hostname }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       folder: "{{folder.result.path}}"
       force: "yes"
       datastore: "{{vm_sdt_datastore}}"
       datacenter: "{{vcenter_datacenter}}"
       name: "vmsdt-collette-clone"
       state: present
       esxi_hostname: "esxi4.becode.org"
       template: "BeCentral/vm/Templates/template-debian-10"
       disk:
         - size_gb: 40
           type: thin
           datastore: "{{vcenter_datastore}}"
       hardware:
         memory_mb: "{{vm_sdt_mem_size}}"
         num_cpus: "{{vm_sdt_cpu_num}}"
         scsi: paravirtual
         memory_reservation_lock: "{{vm_sdt_memory_reservation_lock}}"
         hotadd_cpu: "{{vm_sdt_hotadd_cpu}}"
         hotremove_cpu: "{{vm_sdt_hotremove_cpu}}"
         hotadd_memory: "{{vm_sdt_hotadd_memory}}"
         boot_firmware: "efi"
       networks:
       - name: "{{vm_sdt_network}}"
         start_connected: "{{vm_sdt_start_connected}}"
       wait_for_ip_address: true
     delegate_to: localhost
     register: deploy
     when: true
